name: AWS CD
on:
  push:
    branches:
      - dev
      - homolog
      - prod
  workflow_dispatch:

jobs:
  DeployToAWS:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine AWS Account ID, Region and Stage
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
            echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
            echo "HOSTED_ZONE_ID=${{ secrets.DEV_HOSTED_ZONE_ID }}" >> $GITHUB_ENV
            echo "HOSTED_ZONE_NAME=${{ vars.DEV_HOSTED_ZONE_NAME }}" >> $GITHUB_ENV
            echo "STAGE=dev" >> $GITHUB_ENV
            echo "ACM_CERTIFICATE_ARN=${{ secrets.DEV_ACM_DEVMAUA_CERTIFICATE_ARN }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOML }}" >> $GITHUB_ENV
            echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
            echo "HOSTED_ZONE_ID=${{ secrets.HOML_HOSTED_ZONE_ID }}" >> $GITHUB_ENV
            echo "HOSTED_ZONE_NAME=${{ vars.HOML_HOSTED_ZONE_NAME }}" >> $GITHUB_ENV
            echo "STAGE=homolog" >> $GITHUB_ENV
            echo "ACM_CERTIFICATE_ARN=${{ secrets.HML_ACM_DEVMAUA_CERTIFICATE_ARN }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
            echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
            echo "HOSTED_ZONE_ID=${{ secrets.PROD_HOSTED_ZONE_ID }}" >> $GITHUB_ENV
            echo "HOSTED_ZONE_NAME=${{ vars.PROD_HOSTED_ZONE_NAME }}" >> $GITHUB_ENV
            echo "STAGE=prod" >> $GITHUB_ENV
            echo "ACM_CERTIFICATE_ARN=${{ secrets.PROD_ACM_DEVMAUA_CERTIFICATE_ARN }}" >> $GITHUB_ENV
          else
            echo "Invalid branch name!" && exit 1
          fi

          echo "STACK_NAME=ReservationStackFront${{ github.ref_name }}" >> $GITHUB_ENV
          echo "ALTERNATIVE_DOMAIN_NAME=${{ vars.DOMAIN_NAME }}" >> $GITHUB_ENV

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: github-action-${{ github.run_id }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Installing Dependencies
        run: |
          npm install
          npm install -g aws-cdk

      - name: Fetch config from SSM
        run: |
          STAGE="${{ env.STAGE }}"

          VITE_USER_URL=$(aws ssm get-parameter \
            --name "/reservationmssuser/$STAGE/api/url" \
            --query "Parameter.Value" --output text || true)

          VITE_RESERVATION_URL=$(aws ssm get-parameter \
            --name "/reservationapi/$STAGE/api/url" \
            --query "Parameter.Value" --output text || true)

          VITE_ALERT_URL=$(aws ssm get-parameter \
            --name "/reservationmssalert/$STAGE/api/url" \
            --query "Parameter.Value" --output text || true)

          if [ -n "$VITE_USER_URL" ]; then
            echo "::add-mask::$VITE_USER_URL"
          fi

          if [ -n "$VITE_RESERVATION_URL" ]; then
            echo "::add-mask::$VITE_RESERVATION_URL"
          fi

          if [ -n "$VITE_ALERT_URL" ]; then
            echo "::add-mask::$VITE_ALERT_URL"
          fi

          echo "VITE_USER_URL=$VITE_USER_URL" >> $GITHUB_ENV
          echo "VITE_RESERVATION_URL=$VITE_RESERVATION_URL" >> $GITHUB_ENV
          echo "VITE_ALERT_URL=$VITE_ALERT_URL" >> $GITHUB_ENV

      - name: Validate variables from ssm
        shell: /usr/bin/bash -e {0}
        run: |
          missing=()

          check_var() {
            local key=$1
            local value=$2
            if [ -z "$value" ]; then
              missing+=("$key")
            fi
          }

          check_var "VITE_USER_URL" "$VITE_USER_URL"
          check_var "VITE_RESERVATION_URL" "$VITE_RESERVATION_URL"
          check_var "VITE_ALERT_URL" "$VITE_ALERT_URL"

          if [ ${#missing[@]} -gt 0 ]; then
            echo "❌ Missing environment variables:"
            printf ' - %s\n' "${missing[@]}"
            exit 1
          fi

          echo "✅ All environment variables from ssm are set"

      - name: Build and Export
        run: |
          npm run build
        env:
          VITE_STAGE: ${{ env.STAGE }}
          VITE_AUTH_CLIENT_ID: ${{ vars.VITE_AUTH_CLIENT_ID }}
          VITE_AUTH_TENANT_ID: ${{ vars.VITE_AUTH_TENANT_ID }}
          VITE_USER_URL: ${{ env.VITE_USER_URL }}
          VITE_RESERVATION_URL: ${{ env.VITE_RESERVATION_URL }}
          VITE_ALERT_URL: ${{ env.VITE_ALERT_URL }}

      - name: Setup envs
        run: |
          echo "Stage: ${{ env.STAGE }}"
          echo "AWS_ACCOUNT_ID=${{ env.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "STACK_NAME=${{ env.STACK_NAME }}" >> $GITHUB_ENV
          echo "GITHUB_REF_NAME=${{ env.STAGE }}" >> $GITHUB_ENV
          echo "AWS_BUCKET_ASSETS=${{ vars.AWS_BUCKET_ASSETS }}" >> $GITHUB_ENV
          echo "VITE_USER_URL=${{ env.VITE_USER_URL }}" >> $GITHUB_ENV
          echo "VITE_ALERT_URL=${{ env.VITE_ALERT_URL }}" >> $GITHUB_ENV
          echo "VITE_RESERVATION_URL=${{ env.VITE_RESERVATION_URL }}" >> $GITHUB_ENV

      - name: Deploy with CDK
        env:
          STAGE: ${{ env.STAGE }}
          ACM_CERTIFICATE_ARN: ${{ env.ACM_CERTIFICATE_ARN }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          cd iac
          npm install
          cdk synth
          cdk deploy --require-approval never

      - name: Set CloudFront ID
        run: |
          CLOUD_FRONT_ID=$(aws cloudformation --region ${{env.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='ReservationFrontDistributionId${{env.STAGE}}'].OutputValue" --output text)
          echo "CLOUD_FRONT_ID=$CLOUD_FRONT_ID" >> $GITHUB_ENV

      - name: Set AWS Bucket
        run: |
          echo "Setting AWS Bucket"
          AWS_BUCKET=$(aws cloudformation --region ${{env.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='ReservationFrontBucketName${{env.STAGE}}'].OutputValue" --output text)
          echo "AWS_BUCKET=$AWS_BUCKET" >> $GITHUB_ENV

      - name: Check if bucket exists
        run: |
          if [ -z "${{env.AWS_BUCKET}}" ]; then
            echo "Bucket name is empty!"
            exit 1
          fi
          aws s3 ls s3://${{env.AWS_BUCKET}} || (echo "Bucket does not exist or is inaccessible" && exit 1)

      - name: Upload to S3
        run: |
          aws s3 cp dist s3://${{env.AWS_BUCKET}}/ --recursive --region ${{ env.AWS_REGION }}

      - name: Clear CDN cache
        run: aws cloudfront create-invalidation --distribution-id ${{env.CLOUD_FRONT_ID}} --paths "/*" --region us-east-1
