name: AWS CD
on:
  push:
    branches:
      - dev
      - homolog
      - prod
      - aws-migration
  workflow_dispatch:

jobs:
  DeployToAWS:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Determine AWS Account ID
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "aws-migration" ]]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOMOLOG }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
          else
            echo "Invalid branch name!" && exit 1
          fi
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/checkout@v2
      - name: Setup AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: github-action
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setting stage and stack name
        run: |
          echo "STAGE=${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "STAGE=dev"
          elif [[ "${{ github.ref_name }}" == "aws-migration" ]]; then
            echo "STAGE=aws-migration"
          elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
            echo "STAGE=homolog"
          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
            echo "STAGE=prod"
          else
            echo "Invalid branch name!" && exit 1
          fi
          echo "STACK_NAME=ReservationStackFront${{env.STAGE}}" >> $GITHUB_ENV
      - name: Installing Dependencies
        run: |
          npm install
          npm install -g aws-cdk
      - name: Build and Export
        run: |
          npm run build
        env:
          VITE_STAGE: ${{ env.VITE_STAGE}}
      - name: Setup envs
        run: |
          echo AWS_REGION=${{ vars.AWS_REGION }} >> $GITHUB_ENV
          echo AWS_ACCOUNT_ID=${{ env.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
          echo STACK_NAME=${{ env.STACK_NAME }} >> $GITHUB_ENV
          echo GITHUB_REF_NAME=${{ env.STAGE }} >> $GITHUB_ENV
          echo ACM_CERTIFICATE_ARN=${{ secrets.DEVMAUA_ACM_CERTIFICATE_ARN }} >> $GITHUB_ENV
          echo AWS_BUCKET_ASSETS=${{ vars.AWS_BUCKET_ASSETS }} >> $GITHUB_ENV
          echo VITE_RESERVATION_API=${{ vars.VITE_RESERVATION_API }} >> $GITHUB_ENV
      - name: Deploy with CDK
        run: |
          cd iac
          npm install
          cdk synth
          cdk deploy --require-approval never
      - name: Set CloudFront ID
        run: |
          echo "Stack name: ${{ env.STACK_NAME }}"
          echo "Stage: ${{ env.STAGE }}"
          CLOUD_FRONT_ID=$(aws cloudformation --region ${{vars.AWS_REGION}} describe-stacks --stack-name ${{env.STACK_NAME}} --query "Stacks[0].Outputs[?OutputKey=='ReservationFrontDistributionId${{env.STAGE}}'].OutputValue" --output text)
          echo "CLOUD_FRONT_ID='$CLOUD_FRONT_ID'" >> $GITHUB_ENV
      - name: Set AWS Bucket
        run: |
          echo "Stack name: ${{ env.STACK_NAME }}"
          echo "Stage: ${{ env.STAGE }}"
          AWS_BUCKET=$(aws cloudformation describe-stacks \
            --stack-name ${{ env.STACK_NAME }} \
            --region ${{ vars.AWS_REGION }} \
            --query "Stacks[0].Outputs[?OutputKey=='ReservationFrontBucketName${{ env.STAGE }}'].OutputValue" \
            --output text)
          echo "Extracted AWS_BUCKET: '$AWS_BUCKET'"
          if [ -z "$AWS_BUCKET" ]; then
            echo "::error::Bucket name is empty. Check CloudFormation stack outputs."
            exit 1
          fi
          echo "AWS_BUCKET=$AWS_BUCKET" >> $GITHUB_ENV
      - name: Check if bucket exists
        run: |
          if [ -z "$AWS_BUCKET" ]; then
            echo "Bucket name is empty!"
            exit 1
          fi
          aws s3 ls s3://$AWS_BUCKET || (echo "Bucket does not exist or is inaccessible" && exit 1)
      - name: Upload to S3
        run: aws s3 cp dist s3://${{env.AWS_BUCKET}}/ --recursive --region ${{ vars.AWS_REGION }}
      - name: Clear CDN cache
        run: aws cloudfront create-invalidation --distribution-id ${{env.CLOUD_FRONT_ID}} --paths "/*" --region us-east-1
